openapi: 3.1.0
info:
  version: 0.1.0
  title: Turing Signing Server Reference Documentation
  contact:
    url: "https://tss.stellar.com/"
  license:
    name: GPL-3.0 License
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
  x-logo:
    url: "https://raw.githubusercontent.com/tyvdh/stellar-tss/master/assets/tss-logo.png"
    altText: TSS Home Page
  description: >
    Turing Signing Servers (TSS) provides decentralizated contract creation on Stellar.
tags:
  - name: Turret
    description: View information about a Turret
  - name: txFunctions
    description: Manage and run txFunctions on the Turret
  - name: Control Accounts
    description: Control Turret account information
paths:
  /:
    $ref: "paths/root.yml"
  /.well-known/stellar.toml:
    $ref: "paths/well-known/toml.yml"
  /tx-functions:
    $ref: "paths/tx-functions.yml"
  /tx-functions/{txFunctionHash}:
    $ref: "paths/tx-functions@{txFunctionHash}.yml"
  /ctrl-accounts:
    $ref: "paths/ctrl-accounts.yml"
components:
  securitySchemes:
    fee_auth:
      description: >
        A claimable balance operation submitted to 
        the ledger payable to the turret within the fee limits
        of the turret. See creation example in this 
        [RunKit Example](https://runkit.com/tyvdh/609ae431597d79001ac15ebc)
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-examples:
        header: test
servers:
  - url: "http://valid-tss-address"
