[TSS]
TURRETS = [
  'GB4OYM7TQTJSROWXHOJLKAX2IJ2QN4I6S6GCJH4MGWVTAO5Q5DPNADXX', # self
  'GAMGW7ZESFF2KVGL7EMBBIAXTFAOF3MNI2JBWSPLTGMAKOSVLHDNZMA2', # EverLife.AI
  'GCAQY54O7ABHNQDXNM3YLISXMX2B5M63GLB5SH6AIS66K7UXFYZ2GVPD', # Script3
  'GARBNUK4IZDGKDJTIEWAL6FTY3UDRSRV275X4H5JS2PGCKTZZ3NDYU5U', # Litemint
  'GDZACR7XAJWU3JLJ5TVDOLCVB5DCIY2K7PHDR7ODGCEQTNVENOPHLCF7', # Atemosta
  'GA7FCNDCYS2N4XQER6P2KHK4FDVVM2PJCM3PODAZXC35QNJR5WINT6GO', # Zig3
]
