name = "tss-wrangler"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "dfd716443bca4859850dd27a6f885a60"
workers_dev = true
kv_namespaces = [
   { binding = "META", id = "239e6a0c4c8d47569eb202278fd99e58" },
   { binding = "TX_FUNCTIONS", id = "bb7ba59b38e040bbab7d71dfdb826911" },
   { binding = "TX_FEES", id = "bc666162fd1c44f0b22c605e14c07597" },
   { binding = "TX_SPONSORS", id = "01269d925c44431aaab92c31307e8599" }
]
vars = { STELLAR_NETWORK = "TESTNET", TURRET_ADDRESS = "GB4OYM7TQTJSROWXHOJLKAX2IJ2QN4I6S6GCJH4MGWVTAO5Q5DPNADXX", TURRET_RUN_URL = "https://ylorcf18ii.execute-api.us-east-1.amazonaws.com" }