name = "tss-wrangler"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "a57d90a1bc9cddece62bc238e62054d5"
workers_dev = true
kv_namespaces = [
   { binding = "META", id = "c71080d059c544f7b6c70a7f0a53a87e" },
   { binding = "TX_FUNCTIONS", id = "b9b700cdbd1943b8b848a44dc62d5d7f" },
   { binding = "TX_FEES", id = "5170a0b5ab9f451b9433ad16e25f04ed" },
   { binding = "TX_SPONSORS", id = "0d4cf078935b4278a8b1670182a4890e" }
]
vars = { STELLAR_NETWORK = "TESTNET", TURRET_ADDRESS = "GAATC6A7OOY7P36FTDFEHKHG7OS72A3NTSGM4RA6HJ5GKHUOEVRWGM76", TURRET_RUN_URL = "https://eaynlikyh1.execute-api.us-east-1.amazonaws.com/" }
