name = "tss-wrangler"
type = "javascript"
usage_model = "bundled"
webpack_config = "webpack.config.js"
account_id = "ac332ac2cd58b5c38e54788912d1de9a"
workers_dev = true

kv_namespaces = [
  { binding = "META", id = "548b7fdb50db490c946212176d86c050" },
  { binding = "TX_FUNCTIONS", id = "18013dc5d7eb41bd975d0f86ee78806c" },
  { binding = "TX_FEES", id = "48085fc3eabe4c7989ac67fb00b2546c" }
]

vars = { STELLAR_NETWORK = "TESTNET", HORIZON_URL = "https://horizon-testnet.stellar.org", TURRET_ADDRESS = "GBYCSCR2FIR6PEW26FEQH27EBBDUDRSO2FDRGKBIHPLBOOQGFWPKZE2D", TURRET_RUN_URL = "https://eaynlikyh1.execute-api.us-east-1.amazonaws.com/", XLM_FEE_MIN = 1, XLM_FEE_MAX = 5000, UPLOAD_DIVISOR = 1000, RUN_DIVISOR = 100000 }

[build]
command = "npm i && npm run build"
[build.upload]
format = "modules"
main = "./shim.mjs"