name = "tss-wrangler"
type = "webpack"
usage_model = "bundled"
webpack_config = "webpack.config.js"
account_id = "ba55b7ae9acfb3ed152103e3497c0752"
zone_id = "ac6fd4037592e821162b01bb8faa2f9a"
route = "api.stellarturrets.com/*"
workers_dev = true
kv_namespaces = [
   { binding = "META", id = "1959d98949ba4c8aa9c333b836cdc5ca" },
   { binding = "TX_FUNCTIONS", id = "35d9a95d987b449fa44263f42d366429" },
   { binding = "TX_FEES", id = "6881d21a900540d9b36aa5c6f9465ea5" },
]
vars = { STELLAR_NETWORK = "TESTNET", HORIZON_URL = "https://horizon-testnet.stellar.org", TURRET_ADDRESS = "GB4OYM7TQTJSROWXHOJLKAX2IJ2QN4I6S6GCJH4MGWVTAO5Q5DPNADXX", TURRET_RUN_URL = "https://ylorcf18ii.execute-api.us-east-1.amazonaws.com", TX_FUNCTION_FEE_DAYS_TTL = 180, XLM_FEE_MIN = 1, XLM_FEE_MAX = 10, UPLOAD_DIVISOR = 1000, RUN_DIVISOR = 100000 }