org: script3
app: tss-serverless
service: tss-serverless

package:
  exclude:
    - '**'
  include:
    - dist/**

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    turretBaseUrl: https://tss-wrangler.script3.workers.dev/
    turretAddress: GCAQY54O7ABHNQDXNM3YLISXMX2B5M63GLB5SH6AIS66K7UXFYZ2GVPD
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: '*'

functions:
  run:
    handler: dist/app.default
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 60
    #provisionedConcurrency: 4
    memorySize: 256
    timeout: 8
    events:
      - httpApi:
          method: POST
          path: /{txFunctionHash}
          cors:
            allowedOrigins:
              - ${self:provider.environment.turretBaseUrl}
            allowedHeaders:
              - Content-Type 
              - X-Turret-Data
              - X-Turret-Signature
            allowedMethods:
              - OPTIONS
              - POST
      - httpApi:
          method: GET
          path: /
          cors: true