org: ${env:SLS_ORG}
app: tss-serverless
service: tss-serverless
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    keepOutputDirectory: true
    webpackConfig: webpack.config.js
    includeModules:
      forceInclude:
        - bignumber.js
        - node-fetch
        - stellar-sdk
      forceExclude:
        - aws-sdk
    packager: yarn

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    turretBaseUrl: ${env:SLS_TURRET_BASE_URL}
    turretSigner: ${env:SLS_TURRET_SIGNER_ACCOUNT}
  tracing:
    lambda: true
  httpApi:
    cors: true

functions:
  run:
    handler: src/app.default
    # provisionedConcurrency: 4 # If you're not on a paid plan with AWS you'll need to comment this line out, otherwise you'll get an RunLambdaEvConf error
    memorySize: 256
    timeout: 8
    events:
      - httpApi:
          method: POST
          path: /{txFunctionHash}
      - httpApi:
          method: GET
          path: /