org: ${env:SLS_ORG}
app: tss-serverless
service: tss-serverless
useDotenv: true
variablesResolutionMode: 20210326

package:
  exclude:
    - '**'
  include:
    - dist/**

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    turretBaseUrl: ${env:SLS_TURRET_BASE_URL}
    turretSigner: ${env:SLS_TURRET_SIGNER_ACCOUNT}
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: '*'

functions:
  run:
    handler: dist/app.default
    maximumRetryAttempts: 0
    maximumRecordAgeInSeconds: 60
    provisionedConcurrency: 4 # If you're not on a paid plan with AWS you'll need to comment this line out, otherwise you'll get an RunLambdaEvConf error
    memorySize: 256
    timeout: 8
    events:
      - httpApi:
          method: POST
          path: /{txFunctionHash}
          cors:
            allowedOrigins:
              - ${self:provider.environment.turretBaseUrl}
            allowedHeaders:
              - Content-Type 
              - X-Turret-Data
              - X-Turret-Signature
            allowedMethods:
              - OPTIONS
              - POST
      - httpApi:
          method: GET
          path: /
          cors: true
