name: Deploy Serverless

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
defaults:
  run:
    working-directory: serverless

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: |
           echo "SLS_ORG=${{ secrets.SLS_ORG }}" >> $GITHUB_ENV
           echo "TURRET_BASE_URL=${{ secrets.TURRET_BASE_URL }}" >> $GITHUB_ENV
           echo "TURRET_SIGNER_ACCOUNT=${{ secrets.TURRET_SIGNER_ACCOUNT }}" >> $GITHUB_ENV
      - run: npx envdist -e

      - run: npm ci
      - run: npm run build

      - name: Deploy to AWS with Serverless
        uses: serverless/github-action@v2.17.1
        with:
          args: -c "cd serverless && serverless deploy"
          entrypoint: /bin/bash
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
