name: Deploy Serverless

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: serverless

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - run: npm ci

      - run: npm run build

      - name: Deploy to AWS with Serverless
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
