name: Deploy Wrangler

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@master
        with:
          access_token: ${{ github.token }}
          
      - uses: actions/checkout@v2

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.WRANGLER_API_TOKEN }}
          workingDirectory: wrangler